### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by henkboshoff** [visiondesignzoo/Responsee#2]
Good Day,
I could find no other support contact for Responsee. I am not a developer so I did not use your framework inside GitHub.

I had an issue in mobile view (when the page collapses into mobile view)

ISSUE: When the menu icon is clicked on pages served from the root directory it triggers the dropdown menu. 
But when a page serves from a subdirectory it does not activate the dropdown menu. 

I use server side includes (SSI) to serve the menu into top row of pages. THIS appeared to be the issue:

I SOLVED this by creating a second mainnav2.html, which references css & js as if mainnav2.html sits in a sub-directory (it serves from the root). 

Site here http://www.flamebeing.com

Great framework! I tried skeleton and bootstrap, but Responsee is simpler to grasp.

**Comment by visiondesignzoo** [comment]
Hi Henk,
we've reviewed your website. On the sub-pages is incorrect link to the Java Script files in head. Returns "404 Not Found".

Sincerely,
Responsee Team

**Comment by henkboshoff** [comment]
Got it. Thanks for the fast reponse.
